custom:
  tables:
    subscriptions: WsSubscriptions-${self:custom.stage}

resources:
  Resources:
    WsSubscriptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.subscriptions}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: subscriptionId
            AttributeType: S
          - AttributeName: triggerName
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
          - AttributeName: subscriptionId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: byTriggerName
            KeySchema:
              - AttributeName: triggerName
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
