service: demo-kraken

configValidationMode: off

provider:
  name: aws

plugins:
  - '@kraken.js/serverless'

custom:
  kraken:
    - '@kraken.js/essentials'
    - '@kraken.js/essentials:aws'
    - '@kraken.js/aws'
    - '@kraken.js/aws:subscriptions'

  environment:
    default:
      hello: hello world
    dev:
      hello: salut le monde
    offline:
      hello: olá mundo

functions:
  wsGraphqlHandler:
    handler: src/demo-ws-handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  httpGraphqlHandler:
    handler: src/demo-http-handler.handler
    events:
      - http:
          path: graphql
          method: any
          cors: ${self:custom.cors}
