service: demo-kraken

provider:
  name: aws

plugins:
  - '@kraken.js/serverless'

custom:
  kraken:
    - '@kraken.js/essentials'
    - '@kraken.js/essentials:aws'
    - '@kraken.js/aws'
    - '@kraken.js/aws:sls'
  environment:
    default:
      hello: default hello
    dev:
      hello: hello world
    offline:
      hello: olá mundo

functions:
  wsGraphqlHandler:
    handler: src/ws-handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
