name: Continuous Integration
on:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package:
          - packages/aws
          - packages/auth
          - packages/cli
          - packages/core

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node_modules
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: CLI Setup
        if: matrix.package == 'packages/cli'
        run: |
          npm install -g serverless
          yarn workspace @kraken.js/serverless run package
          yarn workspace @kraken.js/core run package
          yarn workspace @kraken.js/aws run package

      - name: Unit Tests
        working-directory: ${{ matrix.package }}
        run: yarn test --colors --coverage

      - uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.package }}
          directory: ${{ matrix.package }}
