name: Publish
on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package:
          - packages/cli
          - packages/core
          - packages/aws
          - packages/webpack
          - packages/essentials

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Version
        run: yarn version --new-version "0.0.1-${GITHUB_SHA::8}" --no-git-tag-version
        working-directory: ${{ matrix.package }}

      - name: Publish
        run: yarn publish --non-interactive --access public
        working-directory: ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
